version: '3'

services:
 cas1:
    container_name: cas1
    hostname: cas1
    image: cassandra:latest
    volumes:
      - C:/Users/mysk2/PycharmProjects/Cassandra/node1:/var/lib/cassandra/data
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_SEEDS=10.5.0.5, 10.5.0.6, 10.5.0.7
      - CASSANDRA_RPC_ADDRESS=10.5.0.5
    networks:
      mynetwork:
        ipv4_address: 10.5.0.5


 cas2:
  container_name: cas2
  hostname: cas2
  image: cassandra:latest
  volumes:
      - C:/Users/mysk2/PycharmProjects/Cassandra/node2:/var/lib/cassandra/data
  ports:
      - 9043:9042
  depends_on:
    - cas1
  environment:
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_SEEDS=10.5.0.6, 10.5.0.5, 10.5.0.7
      - CASSANDRA_RPC_ADDRESS=10.5.0.6
  networks:
    mynetwork:
      ipv4_address: 10.5.0.6

 cas3:
  container_name: cas3
  hostname: cas3
  image: cassandra:latest
  volumes:
      - C:/Users/mysk2/PycharmProjects/Cassandra/node3:/var/lib/cassandra/data
  ports:
      - 9044:9042
  depends_on:
    - cas1
  environment:
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_SEEDS=10.5.0.7, 10.5.0.5, 10.5.0.6
      - CASSANDRA_RPC_ADDRESS=10.5.0.7
  networks:
    mynetwork:
      ipv4_address: 10.5.0.7


networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
